apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-example
  labels:
    app: crashlooplearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashlooplearning
  template:
    metadata:
      labels:
        app: crashlooplearning
    spec:
      containers:
      - name: crashlooplearning
        image: abhishekf5/crashlooptest:v2
        ports:
        - containerPort: 8000
        resources:
         limits:
          cpu: "25m"
          memory: "25Mi"

Usually it is not recommendatba to extend limit resources of the application, to avoid oom issue from your end, talk to developer and share the application logs to 
him he will check any meory leak or something also if still he asks sahre the thread dump as well.

